Total  Variance (QoQ) % = 
IF(
	ISFILTERED('Date'[Date]),
	ERROR("Time intelligence quick measures can only be grouped or filtered by the Power BI-provided date hierarchy or primary date column."),
	VAR __PREV_Q = CALCULATE([*measure here*], DATEADD('Date'[Date], -1, QUARTER))
	RETURN
		DIVIDE([*measure here*] - __PREV_Q, __PREV_Q)
)

//quarterly variance %