let
    Source = SharePoint.Files("https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC", [ApiVersion = 15]),
    #"Filtered Rows" = Table.SelectRows(Source, each [Folder Path] = "https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC/Shared Documents/Dashboards/Master Data/" and Text.Contains([Name], "Radiant Directory")),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
    #"Expanded Data" = Table.ExpandTableColumn(#"Expanded Table Column1", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}),
    #"Filtered Rows1" = Table.SelectRows(#"Expanded Data", each ([Column5] <> "ADCOM WORLDWIDE" and [Column5] <> "DISTRIBUTION BY AIR" and [Column5] <> "SERVICE BY AIR") and ([Name] = "Company Stores") and ([Column4] <> "RADIANT" and [Column4] <> "RADIANT WORLD TRADE SERVICES")),
    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows1", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company Stores", type text}, {"MANAGER/OWNER", type text}, {"EMAIL", type text}, {"STATION", type text}, {"ADDRESS", type text}, {"Company Stores_1", type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Changed Type", each ([#"MANAGER/OWNER"] <> "MANAGER/OWNER")),
    #"Merged Columns" = Table.AddColumn(#"Filtered Rows2", "Merged", each Text.Combine({[STATION], [#"TOLL FREE #"], [#"LOCAL #"], [ADDRESS]}, ""), type text),
    #"Replaced Value" = Table.ReplaceValue(#"Merged Columns","(","",Replacer.ReplaceText,{"TOLL FREE #", "LOCAL #"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",") ","-",Replacer.ReplaceText,{"TOLL FREE #", "LOCAL #"}),
    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value1", each [Merged] <> null and [Merged] <> ""),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows3",{"Merged"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Company Stores", "Type"}, {"TOLL FREE #", "Phone Number"}, {"LOCAL #", "Local Number"}, {"ADDRESS", "Address"}}),
    #"Filtered Rows5" = Table.SelectRows(#"Renamed Columns", each ([STATION] <> "LAST UPDATED: 8/9/24") and ([Local Number] <> "                               RADIANT CANADA" and [Local Number] <> "                               RADIANT JAPAN" and [Local Number] <> "                               RADIANT MEXICO" and [Local Number] <> "                               RADIANT SHANGHAI" and [Local Number] <> "ADDITIONAL CONTACTS" and [Local Number] <> "RADIANT CANADA" and [Local Number] <> "RADIANT ROAD & RAIL")),
    #"Filled Down" = Table.FillDown(#"Filtered Rows5",{"STATION"}),
    #"Sorted Rows" = Table.Sort(#"Filled Down",{{"STATION", Order.Ascending}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Sorted Rows",{{"STATION", "Station"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns2",{"Type", "Station", "Phone Number", "Local Number", "EMAIL", "Address", "MANAGER/OWNER"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Removed Other Columns","PHL","R25PHL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","PIT","R40PIT",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","PHX","R28PHX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","RMF","R29MFE",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","DCA","R35DCA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","CVG","R45CVG",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","DTW","S63DTW",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","EWR","R41EWR",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","JFK","R46JFK",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","LAX","R81LAX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","MDT","R71MDT",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","IAH ","S33IAH",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","MIA","R98MIA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","MKC","R44MKC",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","Head Office","Canada",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","LRD","R17LRD",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","MFE","R29MFE",Replacer.ReplaceValue,{"Station"})
in
    #"Replaced Value18"