let
    Source = SharePoint.Files("https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC", [ApiVersion = 15]),
    #"Filtered Rows" = Table.SelectRows(Source, each [Folder Path] = "https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC/Shared Documents/Dashboards/Data/" and Text.Contains([Name], "Radiant Directory")),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
    #"Expanded Data" = Table.ExpandTableColumn(#"Expanded Table Column1", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}),
    #"Filtered Rows1" = Table.SelectRows(#"Expanded Data", each ([Name] <> "Company Stores") and ([Column5] <> "ADCOM WORLDWIDE" and [Column5] <> "DISTRIBUTION BY AIR" and [Column5] <> "SERVICE BY AIR")),
    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows1", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"West", type text}, {"MANAGER/OWNER", type text}, {"EMAIL", type text}, {"STATION", type text}, {"ADDRESS", type text}, {"West_1", type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Changed Type1", each ([#"MANAGER/OWNER"] <> "MANAGER/OWNER")),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Filtered Rows2", {{"CODE(2+)", type text}}, "en-US"),{"CODE(2+)", "STATION"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Station"),
    #"Replaced Value" = Table.ReplaceValue(#"Merged Columns","(","",Replacer.ReplaceText,{"TOLL FREE #", "LOCAL #"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",") ","-",Replacer.ReplaceText,{"TOLL FREE #", "LOCAL #"}),
    #"Inserted Merged Column" = Table.AddColumn(#"Replaced Value1", "Merged", each Text.Combine({[Station], [#"TOLL FREE #"], [#"LOCAL #"], [ADDRESS]}, ""), type text),
    #"Filtered Rows3" = Table.SelectRows(#"Inserted Merged Column", each [Merged] <> null and [Merged] <> ""),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows3",{"Merged"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Removed Columns","",null,Replacer.ReplaceValue,{"Station"}),
    #"Filled Down" = Table.FillDown(#"Replaced Value9",{"Station"}),
    #"Renamed Columns" = Table.RenameColumns(#"Filled Down",{{"West", "Type"}, {"TOLL FREE #", "Phone Number"}, {"LOCAL #", "Local Number"}, {"ADDRESS", "Address"}}),
    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"Station", Order.Ascending}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows","117SAT","A17SAT",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","12BUR","BUR",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","16LAS","LAS",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","18SJU","SJU",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","21EUG","EUG",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","24CHS","CHS",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","SSJU","S18SJU",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value8","24CHS","CHS",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value10","25PHL","PHL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","28PHX","PHX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","30 MIA","MIA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","33IAH","IAH",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","34ICT","ICT",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","45CVG ","CVG",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","48OGG","OGG",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","51DFW","DFW",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","54ATL","ATL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","56TUL","TUL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","57TPA","TPA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","65MHT","MHT",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","67SJC","SJC",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","68MKE","MKE",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","69CMH","CMH",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","71MDT","MDT",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","7387","IND",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","77LAX","A77LAX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","79OMA","AGEOMA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","85STL","STL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value31","BPHL","B25PHL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","76LGB","LGB",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","DTW","A63",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value38" = Table.ReplaceValue(#"Replaced Value35","DAGEOMA","AGEOMA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","MIA","MIAAGE",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","45CVG ","CVG",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value42" = Table.ReplaceValue(#"Replaced Value40","51DFW","DFW",Replacer.ReplaceValue,{"Station"}),
    #"Sorted Rows2" = Table.Sort(#"Replaced Value42",{{"Station", Order.Ascending}}),
    #"Replaced Value36" = Table.ReplaceValue(#"Sorted Rows2","DA77LAX","D77LAX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","DATL","D54ATL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value41" = Table.ReplaceValue(#"Replaced Value37","RMDT","R71MDT",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value43" = Table.ReplaceValue(#"Replaced Value41","DPHL","D25PHL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","DPHX","D28PHX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value46" = Table.ReplaceValue(#"Replaced Value44","B81BUR","B81LAX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value47" = Table.ReplaceValue(#"Replaced Value46","SLAS","S16LAS",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value48" = Table.ReplaceValue(#"Replaced Value47","STPA","S57TPA",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value49" = Table.ReplaceValue(#"Replaced Value48","SPHX","S28PHX",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value50" = Table.ReplaceValue(#"Replaced Value49","SSJU","S18SJU",Replacer.ReplaceValue,{"Station"}),
  #"Replaced Value51" = Table.ReplaceValue(#"Replaced Value49","62/67MCO","A62MCO",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value52" = Table.ReplaceValue(#"Replaced Value51","12BUR","BUR",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value53" = Table.ReplaceValue(#"Replaced Value52","16LAS","LAS",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value54" = Table.ReplaceValue(#"Replaced Value53","18SJU","SJU",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value55" = Table.ReplaceValue(#"Replaced Value54","21EUG","EUG",Replacer.ReplaceValue,{"Station"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value55",{"Type", "Station", "Phone Number", "Local Number", "EMAIL", "Address", "MANAGER/OWNER"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Removed Other Columns","73IND","IND",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value11","SLAS","S16LAS",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value45" = Table.ReplaceValue(#"Replaced Value32","SSJU","S18SJU",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value56" = Table.ReplaceValue(#"Replaced Value45","SATL","B92ATL",Replacer.ReplaceValue,{"Station"}),
    #"Replaced Value57" = Table.ReplaceValue(#"Replaced Value56","MIAAGE","MIA",Replacer.ReplaceValue,{"Station"})
in
    #"Replaced Value57"