let
    Source = SharePoint.Files("https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC", [ApiVersion = 15]),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC/Shared Documents/Reports/R33IAH/Pure Storage Monthly Report/Source/")),
    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", let latest = List.Max(#"Filtered Rows"[Date created]) in each [Date created] = latest),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows1",{"Content"}),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Removed Other Columns", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Acct ID", Int64.Type}, {"Bill To Name", type text}, {"Hawb", Int64.Type}, {"Shipper Name", type text}, {"Shipper Addr 1", type text}, {"Shipper Addr 2", type any}, {"Shipper City", type text}, {"Shipper State", type text}, {"Shipper Zip", Int64.Type}, {"Consignee Name", type text}, {"Consignee Addr 1", type text}, {"Consignee Addr 2", type text}, {"Consignee City", type text}, {"Consignee State", type text}, {"Origin A/P", type text}, {"Port of Loading", type any}, {"Dest A/P", type text}, {"Port of Discharge", type any}, {"Pickup Date", type date}, {"Service Level", type text}, {"Delivery Date", type date}, {"Container Pcs", Int64.Type}, {"Cargo Pcs", Int64.Type}, {"Actual Wgt", Int64.Type}, {"Dim Wgt", Int64.Type}, {"Dim UoM", type text}, {"Dim Factor", Int64.Type}, {"Chrg Wgt Lbs", Int64.Type}, {"Chrg Wgt Kg", Int64.Type}, {"Ship Ref", type text}, {"Cons Ref", type any}, {"Bill to Ref", type any}, {"Project #", type any}, {"POD Date", type date}, {"POD Time", type time}, {"POD By", type text}, {"Declared Value", Int64.Type}, {"Insured Value", Int64.Type}, {"Product Description", type any}, {"ETD", type any}, {"ETA", type any}, {"Steamship Line/Carrier", type any}, {"Steam Line Booking", type any}, {"Carrier MBL", type any}, {"Vessel", type any}, {"Container Type", type any}, {"Container Number", type any}, {"Invoice #", Int64.Type}, {"Invoice Date", type date}, {"Posted Date", type date}, {"Business Doc", Int64.Type}, {"Doc Type", type text}, {"Line Item ID", Int64.Type}, {"Line Item", type text}, {"Line Description", type text}, {"Amount", type number}, {"Invoice Total", type number}, {"Cost Complete", type text}, {"Total Cartage Cost", type number}}),
    #"Changed column type" = Table.TransformColumnTypes(#"Changed Type", {{"Acct ID", Int64.Type}, {"Bill To Name", type text}, {"Hawb", Int64.Type}, {"Shipper Name", type text}, {"Shipper Addr 1", type text}, {"Shipper Addr 2", type text}, {"Shipper City", type text}, {"Shipper State", type text}, {"Shipper Zip", Int64.Type}, {"Consignee Name", type text}, {"Consignee Addr 1", type text}, {"Consignee Addr 2", type text}, {"Consignee City", type text}, {"Consignee State", type text}, {"Consignee Zip", type text}, {"Origin A/P", type text}, {"Port of Loading", type text}, {"Dest A/P", type text}, {"Port of Discharge", type text}, {"Pickup Date", type date}, {"Service Level", type text}, {"Delivery Date", type date}, {"Container Pcs", Int64.Type}, {"Cargo Pcs", Int64.Type}, {"Actual Wgt", Int64.Type}, {"Dim Wgt", Int64.Type}, {"Dim UoM", type text}, {"Dim Factor", Int64.Type}, {"Chrg Wgt Lbs", Int64.Type}, {"Chrg Wgt Kg", Int64.Type}, {"Ship Ref", type text}, {"Cons Ref", type text}, {"Bill to Ref", type text}, {"Project #", type text}, {"POD Date", type date}, {"POD Time", type time}, {"POD By", type text}, {"Declared Value", Int64.Type}, {"Insured Value", Int64.Type}, {"Product Description", type text}, {"ETD", type text}, {"ETA", type text}, {"Steamship Line/Carrier", type text}, {"Steam Line Booking", type text}, {"Carrier MBL", type text}, {"Vessel", type text}, {"Container Type", type text}, {"Container Number", type text}, {"Invoice #", Int64.Type}, {"Invoice Date", type date}, {"Posted Date", type date}, {"Business Doc", Int64.Type}, {"Doc Type", type text}, {"Line Item ID", Int64.Type}, {"Line Item", type text}, {"Line Description", type text}, {"Amount", type number}, {"Invoice Total", type number}, {"Cost Complete", type text}, {"Total Cartage Cost", type number}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Acct ID", "Bill To Name", "Shipper Addr 2", "Consignee Addr 1", "Consignee Addr 2", "Consignee City", "Consignee State", "Port of Loading", "Port of Discharge", "Delivery Date", "Container Pcs", "Dim UoM", "Dim Factor", "Chrg Wgt Lbs", "Chrg Wgt Kg", "Project #", "Declared Value", "Insured Value", "ETD", "ETA", "Steamship Line/Carrier", "Steam Line Booking", "Carrier MBL", "Vessel", "Container Type", "Container Number", "Invoice Date", "Posted Date", "Business Doc", "Doc Type", "Line Item ID", "Total Cartage Cost", "Cost Complete"}),
  #"Reordered columns" = Table.ReorderColumns(#"Removed columns",{"Pickup Date", "Hawb", "Shipper Name", "Shipper Addr 1", "Shipper City", "Shipper State", "Shipper Zip", "Ship Ref", "Cons Ref", "Bill to Ref", "Origin A/P", "Dest A/P", "Consignee Name", "Consignee Zip", "Cargo Pcs", "Actual Wgt", "Dim Wgt", "Service Level", "POD By", "POD Date", "POD Time", "Product Description", "Invoice #", "Line Item", "Line Description", "Amount", "Invoice Total"}),
  #"Filtered rows" = Table.SelectRows(#"Reordered columns", each ([Line Item] = "Total")),
    #"Removed columns 1" = Table.RemoveColumns(#"Filtered rows", {"Amount", "Line Description", "Line Item", "Invoice #"}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Removed columns 1", {{"Hawb", type text}}),
  #"Merged queries" = Table.NestedJoin(#"Changed column type 1", {"Hawb"}, Freight, {"Hawb"}, "Freight", JoinKind.LeftOuter),
    #"Expanded Freight" = Table.ExpandTableColumn(#"Merged queries", "Freight", {"Charges"}, {"Charges"}),
  #"Renamed columns" = Table.RenameColumns(#"Expanded Freight", {{"Charges", "Freight"}}),
  #"Merged queries 1" = Table.NestedJoin(#"Renamed columns", {"Hawb"}, Fuel, {"Hawb"}, "Fuel", JoinKind.LeftOuter),
  #"Expanded Fuel" = Table.ExpandTableColumn(#"Merged queries 1", "Fuel", {"Charges"}, {"Charges"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Expanded Fuel", {{"Charges", "Fuel"}}),
  #"Merged queries 2" = Table.NestedJoin(#"Renamed columns 1", {"Hawb"}, Beyond, {"Hawb"}, "Beyond", JoinKind.LeftOuter),
    #"Expanded Beyond" = Table.ExpandTableColumn(#"Merged queries 2", "Beyond", {"Charges"}, {"Charges"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Expanded Beyond", {{"Charges", "Beyond"}}),
  #"Merged queries 3" = Table.NestedJoin(#"Renamed columns 2", {"Hawb"}, Accessorials, {"Hawb"}, "Accessorials", JoinKind.LeftOuter),
  #"Expanded Accessorials" = Table.ExpandTableColumn(#"Merged queries 3", "Accessorials", {"Charges"}, {"Charges"}),
  #"Renamed columns 3" = Table.RenameColumns(#"Expanded Accessorials", {{"Charges", "Accessorials"}}),
    #"Reordered columns 1" = Table.ReorderColumns(#"Renamed columns 3", {"Pickup Date", "Hawb", "Shipper Name", "Shipper Addr 1", "Shipper City", "Shipper State", "Shipper Zip", "Ship Ref", "Origin A/P", "Dest A/P", "Consignee Name", "Consignee Zip", "Cargo Pcs", "Actual Wgt", "Dim Wgt", "Service Level", "POD By", "POD Date", "POD Time", "Product Description", "Freight", "Fuel", "Beyond", "Accessorials", "Invoice Total"}),
  #"Added custom" = Table.AddColumn(#"Reordered columns 1", "Transit Days", each let
    StartDate = [Pickup Date],
    EndDate = [POD Date],
    DaysBetween = List.Dates(StartDate, Duration.Days(EndDate - StartDate), #duration(1,0,0,0)),
    WeekdaysOnly = List.Count(List.Select(DaysBetween, each Date.DayOfWeek(_, Day.Monday) < 5))  
in
    WeekdaysOnly),
  #"Reordered columns 2" = Table.ReorderColumns(#"Added custom", {"Pickup Date", "Hawb", "Shipper Name", "Shipper Addr 1", "Shipper City", "Shipper State", "Shipper Zip", "Ship Ref", "Origin A/P", "Dest A/P", "Consignee Name", "Consignee Zip", "Cargo Pcs", "Actual Wgt", "Dim Wgt", "Service Level", "POD By", "POD Date", "POD Time", "Product Description", "Transit Days", "Freight", "Fuel", "Beyond", "Accessorials", "Invoice Total"}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Reordered columns 2", {{"Transit Days", Int64.Type}}),
  #"Inserted conditional column" = Table.AddColumn(#"Changed column type 2", "On Time", each if [Transit Days] <= 6 then "YES" else "NO"),
  #"Reordered columns 3" = Table.ReorderColumns(#"Inserted conditional column", {"Pickup Date", "Hawb", "Shipper Name", "Shipper Addr 1", "Shipper City", "Shipper State", "Shipper Zip", "Ship Ref", "Origin A/P", "Dest A/P", "Consignee Name", "Consignee Zip", "Cargo Pcs", "Actual Wgt", "Dim Wgt", "Service Level", "POD By", "POD Date", "POD Time", "Product Description", "Transit Days", "On Time", "Freight", "Fuel", "Beyond", "Accessorials", "Invoice Total"}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Reordered columns 3", {{"On Time", type text}}),
  #"Removed columns 2" = Table.RemoveColumns(#"Changed column type 3", {"Shipper Addr 1"}),
  #"Sorted rows" = Table.Sort(#"Removed columns 2", {{"Pickup Date", Order.Ascending}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Sorted rows", {{"Invoice Total", Currency.Type}})
in
    #"Changed column type 4"
