let
    Source = SharePoint.Files("https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC", [ApiVersion = 15]),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://radiantdelivers.sharepoint.com/sites/AsEasyAsECC/Shared Documents/Dashboards/TLA/Source/") and ([Name] = "Radiant Directory Master 0824.xlsx")),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
    #"Expanded Data" = Table.ExpandTableColumn(#"Expanded Table Column1", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}),
    #"Filtered Rows1" = Table.SelectRows(#"Expanded Data", each ([Name] <> "Company Stores") and ([Column5] <> "ADCOM WORLDWIDE" and [Column5] <> "DISTRIBUTION BY AIR" and [Column5] <> "SERVICE BY AIR")),
    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows1", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"West", type text}, {"MANAGER/OWNER", type text}, {"EMAIL", type text}, {"STATION", type text}, {"ADDRESS", type text}, {"West_1", type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Changed Type", each ([#"MANAGER/OWNER"] <> "MANAGER/OWNER")),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Filtered Rows2", {{"CODE(2+)", type text}}, "en-US"),{"CODE(2+)", "STATION"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Station"),
    #"Replaced Value" = Table.ReplaceValue(#"Merged Columns","(","",Replacer.ReplaceText,{"TOLL FREE #", "LOCAL #"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",") ","-",Replacer.ReplaceText,{"TOLL FREE #", "LOCAL #"}),
    #"Inserted Merged Column" = Table.AddColumn(#"Replaced Value1", "Merged", each Text.Combine({[Station], [#"TOLL FREE #"], [#"LOCAL #"], [ADDRESS]}, ""), type text),
    #"Filtered Rows3" = Table.SelectRows(#"Inserted Merged Column", each [Merged] <> null and [Merged] <> ""),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows3",{"Merged"}),
    #"Filtered Rows4" = Table.SelectRows(#"Removed Columns", each ([Station] <> "")),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows4",{{"West", "Type"}, {"TOLL FREE #", "Phone Number"}, {"LOCAL #", "Local Number"}, {"ADDRESS", "Address"}}),
    #"Filtered Rows5" = Table.SelectRows(#"Renamed Columns", each ([Station] <> "LAST UPDATED: 8/9/24")),
    #"Sorted Rows" = Table.Sort(#"Filtered Rows5",{{"Station", Order.Ascending}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows","117SAT","A17SAT",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","12BUR","BUR",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","16LAS","LAS",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","18SJU","SJU",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","21EUG","EUG",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","24CHS","CHS",Replacer.ReplaceText,{"Station"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","SSJU","S18SJU",Replacer.ReplaceValue,{"Station"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value8",{"Type", "Station", "Phone Number", "Local Number", "EMAIL", "Address"})
in
    #"Removed Other Columns"