let
    Source = Folder.Files("W:\source-systems\SAPTM\shipments"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Table Column1",{"Source.Name", "POD SFB", "Equipment Type"}),
    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Removed Columns", {{"Incoterm", type text}, {"Routed", type text}, {"Created On Date", type text}, {"Pick-Up Date (From)", type text}, {"Pick-Up Date (To)", type text}}, "en-US"),{{"House Bill of Lading", Text.Trim, type text}, {"Station name", Text.Trim, type text}, {"Transp. Mode Description", Text.Trim, type text}, {"Traffic Direction", Text.Trim, type text}, {"Movement Type", Text.Trim, type text}, {"Srv Level Description", Text.Trim, type text}, {"Created On Date", Text.Trim, type text}, {"Pick-Up Date (From)", Text.Trim, type text}, {"Pick-Up Date (To)", Text.Trim, type text}, {"Source Location Description", Text.Trim, type text}, {"Destination Location Descripti", Text.Trim, type text}, {"Source Location City", Text.Trim, type text}, {"Source Location Country", Text.Trim, type text}, {"Destination Location City", Text.Trim, type text}, {"Destination Location Country", Text.Trim, type text}, {"Ordering Party Description", Text.Trim, type text}, {"Origin APC", Text.Trim, type text}, {"Dest APC", Text.Trim, type text}, {"Quantity", Text.Trim, type text}, {"Quantity UoM", Text.Trim, type text}, {"Gross Volume", Text.Trim, type text}, {"Gross Vol. UoM", Text.Trim, type text}, {"Gross Weight", Text.Trim, type text}, {"Gr. Wt UoM", Text.Trim, type text}, {"Pro/MAWB No", Text.Trim, type text}, {"Dimensional Weight", Text.Trim, type text}, {"Dimensional Weight UOM", Text.Trim, type text}, {"Source Location Region", Text.Trim, type text}, {"Source Location Zip Code", Text.Trim, type text}, {"Destination Location Region", Text.Trim, type text}, {"Destination Location Zip Code", Text.Trim, type text}, {"Origin ACI Zone", Text.Trim, type text}, {"Dest ACI Zone", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"House Bill of Lading", Text.Clean, type text}, {"Station name", Text.Clean, type text}, {"Transp. Mode Description", Text.Clean, type text}, {"Traffic Direction", Text.Clean, type text}, {"Movement Type", Text.Clean, type text}, {"Incoterm", Text.Clean, type text}, {"Routed", Text.Clean, type text}, {"Srv Level Description", Text.Clean, type text}, {"Created On Date", Text.Clean, type text}, {"Pick-Up Date (From)", Text.Clean, type text}, {"Pick-Up Date (To)", Text.Clean, type text}, {"Source Location Description", Text.Clean, type text}, {"Destination Location Descripti", Text.Clean, type text}, {"Source Location City", Text.Clean, type text}, {"Source Location Country", Text.Clean, type text}, {"Destination Location City", Text.Clean, type text}, {"Destination Location Country", Text.Clean, type text}, {"Ordering Party Description", Text.Clean, type text}, {"Origin APC", Text.Clean, type text}, {"Dest APC", Text.Clean, type text}, {"Quantity", Text.Clean, type text}, {"Quantity UoM", Text.Clean, type text}, {"Gross Volume", Text.Clean, type text}, {"Gross Vol. UoM", Text.Clean, type text}, {"Gross Weight", Text.Clean, type text}, {"Gr. Wt UoM", Text.Clean, type text}, {"Pro/MAWB No", Text.Clean, type text}, {"Dimensional Weight", Text.Clean, type text}, {"Dimensional Weight UOM", Text.Clean, type text}, {"Source Location Region", Text.Clean, type text}, {"Source Location Zip Code", Text.Clean, type text}, {"Destination Location Region", Text.Clean, type text}, {"Destination Location Zip Code", Text.Clean, type text}, {"Origin ACI Zone", Text.Clean, type text}, {"Dest ACI Zone", Text.Clean, type text}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Cleaned Text",{{"House Bill of Lading", type text}, {"Station name", type text}, {"Transp. Mode Description", type text}, {"Traffic Direction", type text}, {"Movement Type", type text}, {"Incoterm", type text}, {"Routed", type text}, {"Srv Level Description", type text}, {"Created On Date", type date}, {"Pick-Up Date (From)", type date}, {"Pick-Up Date (To)", type date}, {"Source Location Description", type text}, {"Destination Location Descripti", type text}, {"Source Location City", type text}, {"Source Location Country", type text}, {"Destination Location City", type text}, {"Destination Location Country", type text}, {"Ordering Party Description", type text}, {"Origin APC", type text}, {"Dest APC", type text}, {"Quantity UoM", type text}, {"Gross Vol. UoM", type text}, {"Gr. Wt UoM", type text}, {"Pro/MAWB No", type text}, {"Dimensional Weight UOM", type text}, {"Source Location Region", type text}, {"Source Location Zip Code", type text}, {"Destination Location Region", type text}, {"Destination Location Zip Code", type text}, {"Origin ACI Zone", type text}, {"Dest ACI Zone", type text}, {"Gross Volume", type number}, {"Quantity", Int64.Type}, {"Gross Weight", type number}, {"Dimensional Weight", type number}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type",{{"Source Location Description", Text.Proper, type text}, {"Destination Location Descripti", Text.Proper, type text}, {"Ordering Party Description", Text.Proper, type text}, {"Destination Location City", Text.Proper, type text}, {"Source Location City", Text.Proper, type text}})
in
    #"Capitalized Each Word"