// cleaned data - file path: dev-fsx/BI-Data-Prod/TLA/source-data/Shipments.xlsx
let
    Source = posting, // file path: dev-fsx/BI-Data-Prod/source-system/SAPTM/posting
    #"Removed Columns" = Table.RemoveColumns(Source,{"Source.Name", "MAWB", "LH Vendor", "LH Amount", "LH Currency", "PU Vendor", "PU Amount", "PU Currency", "DL Vendor", "DL Amount", "DL Currency", "Misc Vendor", "Misc Amount", "Misc Currency", "Station", "Station Currency", "G&A", "G&A Currency", "Variance", "Total Variance"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "Posted Date", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Posted Date.1", "Posted Date.2", "Posted Date.3"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Posted Date.1", type date}, {"Posted Date.2", type time}, {"Posted Date.3", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Posted Date.2", "Posted Time"}, {"Posted Date.3", "Posted TZ"}, {"Posted Date.1", "Posted Date"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Bill To Party ID] <> null)),
    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Filtered Rows", {{"Invoice Date", type text}, {"Posted Date", type text}, {"Posted Time", type text}, {"Gross", type text}}, "en-US"),{{"House Bill Number", Text.Trim, type text}, {"Station Name", Text.Trim, type text}, {"Transportation Mode", Text.Trim, type text}, {"Bill To Party ID", Text.Trim, type text}, {"Bill To Party Name", Text.Trim, type text}, {"Invoice Number", Text.Trim, type text}, {"Invoice Date", Text.Trim, type text}, {"Posted Date", Text.Trim, type text}, {"Posted Time", Text.Trim, type text}, {"Posted TZ", Text.Trim, type text}, {"Gross", Text.Trim, type text}, {"Gross Currency", Text.Trim, type text}, {"Document Type", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"House Bill Number", Text.Clean, type text}, {"Station Name", Text.Clean, type text}, {"Transportation Mode", Text.Clean, type text}, {"Bill To Party ID", Text.Clean, type text}, {"Bill To Party Name", Text.Clean, type text}, {"Invoice Number", Text.Clean, type text}, {"Invoice Date", Text.Clean, type text}, {"Posted Date", Text.Clean, type text}, {"Posted Time", Text.Clean, type text}, {"Posted TZ", Text.Clean, type text}, {"Gross", Text.Clean, type text}, {"Gross Currency", Text.Clean, type text}, {"Document Type", Text.Clean, type text}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Cleaned Text",{{"Gross", Currency.Type}, {"Gross Currency", type text}, {"Document Type", type text}, {"House Bill Number", type text}, {"Station Name", type text}, {"Transportation Mode", type text}, {"Bill To Party ID", type text}, {"Bill To Party Name", type text}, {"Invoice Number", type text}, {"Invoice Date", type date}, {"Posted Date", type date}, {"Posted Time", type time}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type1",{{"Bill To Party Name", Text.Proper, type text}})
in
    #"Capitalized Each Word"